#!/usr/bin/env python3
"""Generate x86_64 AROS lazy ABI thunks for Node's shared V8 boundary.

The input is Node's already-built libnode archive and the exact Chromium V8
monolith engulfed by v8.library.  Only undefined Node V8/cppgc function symbols
that are present in the monolith are emitted.  Each thunk preserves the SysV
integer and vector argument registers, resolves once through
NodeV8ResolveEngineSymbol(), caches the address, and tail-jumps to v8.library.
No V8 object code is copied into the consumer archive.
"""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path


V8_PREFIXES = (
    "_Z8V8_Fatal",
    "_ZN12v8_inspector",
    "_ZNK12v8_inspector",
    "_ZN2v8",
    "_ZNK2v8",
    "_ZN3v8",
    "_ZNK3v8",
    "_ZN5cppgc",
    "_ZNK5cppgc",
)


def nm_symbols(nm: str, archive: Path, undefined: bool) -> dict[str, str]:
    command = [nm, "--format=posix"]
    if undefined:
        command.append("-u")
    else:
        command.append("--defined-only")
    command.append(str(archive))

    output = subprocess.check_output(command, text=True)
    symbols: dict[str, str] = {}
    for line in output.splitlines():
        fields = line.split()
        if len(fields) < 2:
            continue
        name, kind = fields[0], fields[1]
        if name.startswith(V8_PREFIXES):
            symbols[name] = kind
    return symbols


def emit_thunk(index: int, symbol: str) -> str:
    return f"""
    .p2align 4
    .globl {symbol}
    .type {symbol},@function
{symbol}:
    movq .Lnode_v8_cache_{index}(%rip), %r11
    testq %r11, %r11
    jne .Lnode_v8_jump_{index}

    pushq %rax
    pushq %rdi
    pushq %rsi
    pushq %rdx
    pushq %rcx
    pushq %r8
    pushq %r9
    subq $128, %rsp
    movdqu %xmm0,   0(%rsp)
    movdqu %xmm1,  16(%rsp)
    movdqu %xmm2,  32(%rsp)
    movdqu %xmm3,  48(%rsp)
    movdqu %xmm4,  64(%rsp)
    movdqu %xmm5,  80(%rsp)
    movdqu %xmm6,  96(%rsp)
    movdqu %xmm7, 112(%rsp)

    leaq .Lnode_v8_name_{index}(%rip), %rdi
    call NodeV8ResolveEngineSymbol
    movq %rax, %r11
    movq %rax, .Lnode_v8_cache_{index}(%rip)

    movdqu   0(%rsp), %xmm0
    movdqu  16(%rsp), %xmm1
    movdqu  32(%rsp), %xmm2
    movdqu  48(%rsp), %xmm3
    movdqu  64(%rsp), %xmm4
    movdqu  80(%rsp), %xmm5
    movdqu  96(%rsp), %xmm6
    movdqu 112(%rsp), %xmm7
    addq $128, %rsp
    popq %r9
    popq %r8
    popq %rcx
    popq %rdx
    popq %rsi
    popq %rdi
    popq %rax

    testq %r11, %r11
    je .Lnode_v8_missing_{index}
.Lnode_v8_jump_{index}:
    jmp *%r11
.Lnode_v8_missing_{index}:
    ud2
    .size {symbol}, .-{symbol}
"""


def generate(node_archive: Path, engine_archive: Path, nm: str) -> str:
    undefined = nm_symbols(nm, node_archive, undefined=True)
    defined = nm_symbols(nm, engine_archive, undefined=False)
    callable_kinds = {"T", "t", "W", "w"}
    symbols = sorted(
        name
        for name, kind in undefined.items()
        if name in defined and defined[name] in callable_kinds
    )

    if not symbols:
        raise RuntimeError("no shared Node/V8 text symbols found")

    chunks = [
        "/* Generated by generate-abi-stubs.py; do not edit. */",
        "    .text",
        *[emit_thunk(index, symbol) for index, symbol in enumerate(symbols)],
        "    .section .rodata",
    ]
    for index, symbol in enumerate(symbols):
        chunks.append(f'.Lnode_v8_name_{index}:\n    .asciz "{symbol}"')

    chunks.append("    .section .bss")
    for index in range(len(symbols)):
        chunks.append(
            f"    .p2align 3\n.Lnode_v8_cache_{index}:\n    .quad 0"
        )

    chunks.extend(
        (
            '    .section .note.GNU-stack,"",@progbits',
            f"/* NODE_V8_ABI_STUB_COUNT={len(symbols)} */",
            "",
        )
    )
    return "\n".join(chunks)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--nm", required=True)
    parser.add_argument("--node-archive", type=Path, required=True)
    parser.add_argument("--needed-object", type=Path, action="append",
                        default=[])
    parser.add_argument("--engine-archive", type=Path, required=True)
    parser.add_argument("--provided-object", type=Path, action="append",
                        default=[])
    parser.add_argument("--output", type=Path, required=True)
    arguments = parser.parse_args()

    undefined = nm_symbols(arguments.nm, arguments.node_archive,
                           undefined=True)
    for object_file in arguments.needed_object:
        undefined.update(nm_symbols(arguments.nm, object_file,
                                    undefined=True))
    defined = nm_symbols(arguments.nm, arguments.engine_archive,
                         undefined=False)
    provided: dict[str, str] = {}
    for object_file in arguments.provided_object:
        provided.update(nm_symbols(arguments.nm, object_file,
                                   undefined=False))
    callable_kinds = {"T", "t", "W", "w"}
    selected = sorted(
        name for name in undefined
        if name not in provided and defined.get(name) in callable_kinds
    )
    if not selected:
        raise RuntimeError("no shared Node/V8 text symbols found")

    chunks = [
        "/* Generated by generate-abi-stubs.py; do not edit. */",
        "    .text",
        *[emit_thunk(index, symbol)
          for index, symbol in enumerate(selected)],
        "    .section .rodata",
    ]
    for index, symbol in enumerate(selected):
        chunks.append(f'.Lnode_v8_name_{index}:\n    .asciz "{symbol}"')
    chunks.append("    .section .bss")
    for index in range(len(selected)):
        chunks.append(
            f"    .p2align 3\n.Lnode_v8_cache_{index}:\n    .quad 0"
        )
    chunks.extend(('    .section .note.GNU-stack,"",@progbits',
                   f"/* NODE_V8_ABI_STUB_COUNT={len(selected)} */", ""))
    output = "\n".join(chunks)
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(output)


if __name__ == "__main__":
    main()
