#!/usr/bin/env python3
"""Generate lazy x86_64 ABI thunks for libuv functions inside uv1.library."""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path


def symbols(nm: str, archive: Path, mode: str) -> dict[str, str]:
    command = [nm, "--format=posix"]
    if mode == "undefined":
        command.append("-u")
    else:
        command.append("--defined-only")
    command.append(str(archive))
    result: dict[str, str] = {}
    for line in subprocess.check_output(command, text=True).splitlines():
        fields = line.split()
        if len(fields) >= 2 and fields[0].startswith("uv_"):
            result[fields[0]] = fields[1]
    return result


def thunk(index: int, name: str) -> str:
    return f"""
    .p2align 4
    .globl {name}
    .type {name},@function
{name}:
    movq .Luv_cache_{index}(%rip), %r11
    testq %r11, %r11
    jne .Luv_jump_{index}
    pushq %rax
    pushq %rdi
    pushq %rsi
    pushq %rdx
    pushq %rcx
    pushq %r8
    pushq %r9
    subq $128, %rsp
    movdqu %xmm0,   0(%rsp)
    movdqu %xmm1,  16(%rsp)
    movdqu %xmm2,  32(%rsp)
    movdqu %xmm3,  48(%rsp)
    movdqu %xmm4,  64(%rsp)
    movdqu %xmm5,  80(%rsp)
    movdqu %xmm6,  96(%rsp)
    movdqu %xmm7, 112(%rsp)
    leaq .Luv_name_{index}(%rip), %rdi
    call uv_aros_find_internal_symbol
    movq %rax, %r11
    movq %rax, .Luv_cache_{index}(%rip)
    movdqu   0(%rsp), %xmm0
    movdqu  16(%rsp), %xmm1
    movdqu  32(%rsp), %xmm2
    movdqu  48(%rsp), %xmm3
    movdqu  64(%rsp), %xmm4
    movdqu  80(%rsp), %xmm5
    movdqu  96(%rsp), %xmm6
    movdqu 112(%rsp), %xmm7
    addq $128, %rsp
    popq %r9
    popq %r8
    popq %rcx
    popq %rdx
    popq %rsi
    popq %rdi
    popq %rax
    testq %r11, %r11
    je .Luv_missing_{index}
.Luv_jump_{index}:
    jmp *%r11
.Luv_missing_{index}:
    ud2
    .size {name}, .-{name}
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--nm", required=True)
    parser.add_argument("--needed-archive", type=Path, action="append",
                        required=True)
    parser.add_argument("--link-archive", type=Path, required=True)
    parser.add_argument("--library-module", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    needed: dict[str, str] = {}
    for archive in args.needed_archive:
        needed.update(symbols(args.nm, archive, "undefined"))
    exported = symbols(args.nm, args.link_archive, "defined")
    internal = symbols(args.nm, args.library_module, "defined")
    callable_kinds = {"T", "t", "W", "w"}
    selected = sorted(
        name for name in needed
        if name not in exported and internal.get(name) in callable_kinds
    )
    if not selected:
        raise RuntimeError("no unexported uv1.library functions found")

    output = ["/* Generated by generate-abi-stubs.py; do not edit. */",
              "    .text"]
    output.extend(thunk(index, name) for index, name in enumerate(selected))
    output.append("    .section .rodata")
    for index, name in enumerate(selected):
        output.append(f'.Luv_name_{index}:\n    .asciz "{name}"')
    output.append("    .section .bss")
    for index in range(len(selected)):
        output.append(f"    .p2align 3\n.Luv_cache_{index}:\n    .quad 0")
    output.extend(('    .section .note.GNU-stack,"",@progbits',
                   f"/* UV1_ABI_STUB_COUNT={len(selected)} */", ""))

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(output))


if __name__ == "__main__":
    main()
